# Analisis exploratorio

Acontinuacion se realiza analisis ex...

### 1) Carga y exploracion

In [1]:
import pandas as pd
import numpy as np

In [ ]:
# Carga
df = pd.read_csv('../Archivos/base_datos_restaurantes_USA_v2.csv')

# df = pd.read_csv('../../Carpeta_Destino/nombre_del_archivo.csv')
    # cada carpeta atras de la carpeta actual se indica con ../, y si son 2 carpetas atras se indica con ../../, y asi sucesivamente.

print("--- 1.1 Primeras filas del DataFrame ---")
display(df.head())

print("\n--- 1.2 Información general del DataFrame ---")
display(df.info())

print("\n--- 1.3 Estadísticas descriptivas de las columnas numéricas ---")
display(df.describe())

--- 1.1 Primeras filas del DataFrame ---

,id_persona,nombre,apellido,edad,genero,ciudad_residencia,estrato_socioeconomico,frecuencia_visita,promedio_gasto_comida,ocio,consume_licor,preferencias_alimenticias,membresia_premium,telefono_contacto,correo_electronico,tipo_de_pago_mas_usado,ingresos_mensuales
0,2550327378,Jackson,Gomez,31.0,Masculino,Miami,Alto,6,67.51,Sí,No,Vegetariano,Sí,(830)220-1926,NaN,Efectivo,6425
1,9446112038,Samantha,Soto,40.0,Femenino,Denver,Medio,2,44.92,Sí,Sí,Mariscos,No,881-476-1426,NaN,Efectivo,2374
2,3098363243,Terry,Adams,62.0,Femenino,Denver,Bajo,2,9.24,Sí,Sí,Vegetariano,No,NaN,diana74@example.net,Efectivo,1110
3,4013002847,James,Shannon,41.0,Masculino,Boston,Alto,5,30.74,Sí,Sí,Carnes,Sí,NaN,scottfrey@example.com,Tarjeta,6931
4,7372911048,Susan,Jones,49.0,Femenino,San Diego,Bajo,0,0.00,No,No,Carnes,No,243.248.8919,glassgary@example.org,Tarjeta,1350

--- 1.2 Información general del DataFrame ---
<class 'pandas.DataFrame'>
RangeIndex: 30000 entries, 0 to 29999
Data columns (total 17 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   id_persona                 30000 non-null  int64
 1   nombre                     30000 non-null  str
 2   apellido                   30000 non-null  str
 3   edad                       29899 non-null  float64
 4   genero                     30000 non-null  str
 5   ciudad_residencia          30000 non-null  str
 6   estrato_socioeconomico     30000 non-null  str
 7   frecuencia_visita          30000 non-null  int64
 8   promedio_gasto_comida      29855 non-null  float64
 9   ocio                       30000 non-null  str
 10  consume_licor              30000 non-null  str
 11  preferencias_alimenticias  28597 non-null  str
 12  membresia_premium          30000 non-null  str
 13  telefono_contacto          14834 non-null  str
 14  correo_electronico         14928 non-null  str
 15  tipo_de_pago_mas_usado     30000 non-null  str
 16  ingresos_mensuales         30000 non-null  int64
dtypes: float64(2), int64(3), str(12)
memory usage: 6.0 MB

None

--- 1.3 Estadísticas descriptivas de las columnas numéricas ---

,id_persona,edad,frecuencia_visita,promedio_gasto_comida,ingresos_mensuales
count,3.000000e+04,29899.000000,30000.000000,29855.000000,30000.000000
mean,5.504765e+09,49.665006,3.896133,32.603452,5389.755867
std,2.602799e+09,23.839550,2.741532,26.402601,4538.491728
min,1.000153e+09,-5.000000,-3.000000,0.000000,800.000000
25%,3.243617e+09,33.000000,2.000000,13.290000,1860.000000
50%,5.515865e+09,49.000000,4.000000,25.510000,3402.000000
75%,7.754426e+09,65.000000,5.000000,44.400000,7761.000000
max,9.999627e+09,300.000000,10.000000,149.970000,17999.000000

### 2) Limpieza

In [30]:
df_copy = df.copy()

In [31]:
# ingre3sos por ciudad
ingresos_por_ciudad = df_copy.groupby('ciudad_residencia')['ingresos_mensuales'].sum()
display(ingresos_por_ciudad)

ciudad_residencia
Boston       14411131
Chicago      28009212
Dallas       12649134
Denver       13433559
Houston      10572549
Miami        20633354
NYC          22809174
Phoenix       7925870
San Diego    18717639
Seattle      12531054
Name: ingresos_mensuales, dtype: int64

In [32]:
# display(ingresos_por_ciudad.to_frame().style.format("{:,}"))

In [33]:
# import pandas as pd
# pd.options.display.float_format = '{:,.0f}'.format

In [34]:
df_copy.isnull().sum().sort_values(ascending=False)

telefono_contacto            15166
correo_electronico           15072
preferencias_alimenticias     1403
promedio_gasto_comida          145
edad                           101
id_persona                       0
genero                           0
apellido                         0
nombre                           0
frecuencia_visita                0
estrato_socioeconomico           0
ciudad_residencia                0
ocio                             0
membresia_premium                0
consume_licor                    0
tipo_de_pago_mas_usado           0
ingresos_mensuales               0
dtype: int64

In [35]:
# Imputación de valores faltantes para edad
df_copy['correo_electronico'] = df_copy['correo_electronico'].fillna('No especificado')

In [36]:
# rellenar con na edad fuera de 18 y 80 años
df_copy['edad'] = df_copy['edad'].apply(lambda x: x if (x is not None and 18 <= x <= 80) else np.nan)

In [37]:
df_copy.isnull().sum().sort_values(ascending=False)

telefono_contacto            15166
preferencias_alimenticias     1403
edad                           308
promedio_gasto_comida          145
id_persona                       0
genero                           0
ciudad_residencia                0
apellido                         0
nombre                           0
frecuencia_visita                0
estrato_socioeconomico           0
consume_licor                    0
ocio                             0
membresia_premium                0
correo_electronico               0
tipo_de_pago_mas_usado           0
ingresos_mensuales               0
dtype: int64

In [38]:
edad_promedio_genero = df_copy.groupby(['genero','estrato_socioeconomico'])['edad'].transform('median')

df_copy['edad'] = df_copy['edad'].fillna(edad_promedio_genero)

In [39]:
df_copy.isnull().sum().sort_values(ascending=False)

telefono_contacto            15166
preferencias_alimenticias     1403
promedio_gasto_comida          145
id_persona                       0
nombre                           0
genero                           0
ciudad_residencia                0
edad                             0
apellido                         0
frecuencia_visita                0
estrato_socioeconomico           0
consume_licor                    0
ocio                             0
membresia_premium                0
correo_electronico               0
tipo_de_pago_mas_usado           0
ingresos_mensuales               0
dtype: int64

## Integración api Yelp

In [40]:
df_yelp = pd.read_csv('restaurante_api_yelp_miami.csv')
display(df_yelp.head(3))

,alias,title,id,name,review_count,rating,price,coordinates_latitude,coordinates_longitude,location_address1
0,cuban,Cuban,UXHxLN3DcDGI57uDIfCuJA,Old's Havana Cuban Bar & Cocina,3189,4.4,$$,25.765607,-80.219218,1442 SW 8th St
1,bars,Bars,UXHxLN3DcDGI57uDIfCuJA,Old's Havana Cuban Bar & Cocina,3189,4.4,$$,25.765607,-80.219218,1442 SW 8th St
2,venues,Venues & Event Spaces,UXHxLN3DcDGI57uDIfCuJA,Old's Havana Cuban Bar & Cocina,3189,4.4,$$,25.765607,-80.219218,1442 SW 8th St

In [41]:
df_copy_miami = df_copy[df_copy['ciudad_residencia'] == 'Miami']
display(df_copy_miami.head(3))

,id_persona,nombre,apellido,edad,genero,ciudad_residencia,estrato_socioeconomico,frecuencia_visita,promedio_gasto_comida,ocio,consume_licor,preferencias_alimenticias,membresia_premium,telefono_contacto,correo_electronico,tipo_de_pago_mas_usado,ingresos_mensuales
0,2550327378,Jackson,Gomez,31.0,Masculino,Miami,Alto,6,67.51,Sí,No,Vegetariano,Sí,(830)220-1926,No especificado,Efectivo,6425
16,6139475525,Andrew,Soto,18.0,Masculino,Miami,Muy Alto,9,26.60,Sí,Sí,Vegetariano,Sí,2859380942,ssteele@example.net,App,13452
37,5358661821,Elizabeth,Brown,79.0,Femenino,Miami,Muy Alto,6,28.43,No,No,Mariscos,Sí,(464)992-9070x38394,No especificado,Efectivo,14072

In [42]:
df_yelp['alias'].unique()

array(['cuban', 'bars', 'venues', 'asianfusion', 'steak', 'cocktailbars',
       'mediterranean', 'italian', 'spanish', 'coffee', 'sandwiches',
       'korean', 'bbq', 'hotpot', 'sushi', 'wine_bars', 'pizza',
       'seafood', 'tradamerican', 'sportsbars', 'newamerican', 'lounges',
       'mexican', 'indpak', 'greek', 'lebanese', 'vegetarian',
       'foodstands', 'cajun', 'jazzandblues', 'french', 'japanese',
       'peruvian', 'bubbletea', 'ramen', 'tacos', 'mideastern', 'arabian',
       'portuguese', 'puertorican', 'tapas', 'breakfast_brunch',
       'desserts', 'cafes', 'foodtrucks', 'noodles', 'izakaya', 'salad',
       'vegan', 'empanadas', 'thai', 'hotdogs', 'juicebars', 'latin',
       'argentine', 'butcher', 'chinese', 'caribbean', 'musicvenues',
       'hotdog', 'chicken_wings', 'modern_european', 'turkish', 'basque',
       'fooddeliveryservices', 'beer_and_wine', 'karaoke', 'brazilian',
       'irish', 'irish_pubs', 'burgers', 'gastropubs', 'soulfood',
       'tapasmallplates', 'persian', 'raw_food', 'hotels', 'restaurants',
       'beerbar', 'polish', 'dimsum', 'panasian', 'nicaraguan',
       'taiwanese', 'chickenshop', 'buffets', 'bakeries', 'comfortfood',
       'acaibowls', 'poke', 'food_court'], dtype=object)

In [43]:
df_copy_miami['preferencias_alimenticias'].unique()

array(['Vegetariano', 'Mariscos', 'Carnes', 'Otro', 'Pescado', nan,
       'Vegano'], dtype=object)

In [44]:
categorias_restaurantes = {
    "Carnes": [
        "steak", "bbq", "hotdogs", "hotdog", "chicken_wings", 
        "butcher", "brazilian", "burgers", "chickenshop", "argentine"
    ],
    "Mariscos": [
        "seafood", "cajun"
    ],
    "Pescado": [
        "sushi", "poke"
    ],
    "Vegetariano": [
        "vegetarian", "salad"
    ],
    "Vegano": [
        "vegan", "raw_food", "juicebars", "acaibowls"
    ],
    "Otro": [
        "cuban", "bars", "venues", "asianfusion", "cocktailbars", 
        "mediterranean", "italian", "spanish", "coffee", "sandwiches", 
        "korean", "hotpot", "wine_bars", "pizza", "tradamerican", 
        "sportsbars", "newamerican", "lounges", "mexican", "indpak", 
        "greek", "lebanese", "foodstands", "jazzandblues", "french", 
        "japanese", "peruvian", "bubbletea", "ramen", "tacos", 
        "mideastern", "arabian", "portuguese", "puertorican", "tapas", 
        "breakfast_brunch", "desserts", "cafes", "foodtrucks", "noodles", 
        "izakaya", "empanadas", "thai", "latin", "chinese", "caribbean", 
        "musicvenues", "modern_european", "turkish", "basque", 
        "fooddeliveryservices", "beer_and_wine", "karaoke", "irish", 
        "irish_pubs", "gastropubs", "soulfood", "tapasmallplates", 
        "persian", "hotels", "restaurants", "beerbar", "polish", 
        "dimsum", "panasian", "nicaraguan", "taiwanese", "buffets", 
        "bakeries", "comfortfood", "food_court"
    ],
    None: [] # Representa el valor 'nan' de tu lista
}

In [60]:
mejores_opciones = []

for categoria, alias_list in categorias_restaurantes.items():
    categoria_filtro = '|'.join(alias_list)
    
    #aplicar filtro
    df_filtrado = df_yelp[df_yelp['alias'].str.contains(categoria_filtro, case=False, na=False)]

    #filtro top 1
    df_top = df_filtrado.sort_values(by='rating', ascending=False).iloc[0]
    
    # consolidado
    mejores_opciones.append({
        'preferencias_alimenticias': categoria,
        'nombre_restaurante': df_top['title'],
        'rating': df_top['rating'],
        'review_count': df_top['review_count'],
        'direccion': df_top['location_address1'],
    })

In [61]:
df_resturantes_recomendados = pd.DataFrame(mejores_opciones)

In [62]:
df_resturantes_recomendados

,preferencias_alimenticias,nombre_restaurante,rating,review_count,direccion
0,Carnes,Chicken Wings,5.0,1,950 NW Le Jeune Rd
1,Mariscos,Seafood,4.7,145,62 NW 27th St
2,Pescado,Sushi Bars,4.8,181,197 NW 62nd St
3,Vegetariano,Salad,4.7,59,3176 Commodore Plz
4,Vegano,Vegan,4.4,144,137 Giralda Ave
5,Otro,Bars,5.0,9,2280 SW 22nd St
6,None,Mexican,5.0,9,2280 SW 22nd St

### Unir mejor restaurante de acuer a la preferencia

In [58]:
# df_copy_miami

In [59]:
df_copy_miami = df_copy_miami.merge(df_resturantes_recomendados, left_on='preferencias_alimenticias', right_on='categoria', how='left')
df_copy_miami.head(3)

,id_persona,nombre,apellido,edad,genero,ciudad_residencia,estrato_socioeconomico,frecuencia_visita,promedio_gasto_comida,ocio,...,categoria_x,nombre_restaurante_x,rating_x,review_count_x,direccion_x,categoria_y,nombre_restaurante_y,rating_y,review_count_y,direccion_y
0,2550327378,Jackson,Gomez,31.0,Masculino,Miami,Alto,6,67.51,Sí,...,Vegetariano,Salad,4.7,59,3176 Commodore Plz,Vegetariano,Salad,4.7,59,3176 Commodore Plz
1,6139475525,Andrew,Soto,18.0,Masculino,Miami,Muy Alto,9,26.60,Sí,...,Vegetariano,Salad,4.7,59,3176 Commodore Plz,Vegetariano,Salad,4.7,59,3176 Commodore Plz
2,5358661821,Elizabeth,Brown,79.0,Femenino,Miami,Muy Alto,6,28.43,No,...,Mariscos,Seafood,4.7,145,62 NW 27th St,Mariscos,Seafood,4.7,145,62 NW 27th St

In [63]:
df_copy_miami = df_copy_miami.merge(df_resturantes_recomendados, on='preferencias_alimenticias', how='left')
df_copy_miami.head(3)

,id_persona,nombre,apellido,edad,genero,ciudad_residencia,estrato_socioeconomico,frecuencia_visita,promedio_gasto_comida,ocio,...,direccion_x,categoria_y,nombre_restaurante_y,rating_y,review_count_y,direccion_y,nombre_restaurante,rating,review_count,direccion
0,2550327378,Jackson,Gomez,31.0,Masculino,Miami,Alto,6,67.51,Sí,...,3176 Commodore Plz,Vegetariano,Salad,4.7,59,3176 Commodore Plz,Salad,4.7,59,3176 Commodore Plz
1,6139475525,Andrew,Soto,18.0,Masculino,Miami,Muy Alto,9,26.60,Sí,...,3176 Commodore Plz,Vegetariano,Salad,4.7,59,3176 Commodore Plz,Salad,4.7,59,3176 Commodore Plz
2,5358661821,Elizabeth,Brown,79.0,Femenino,Miami,Muy Alto,6,28.43,No,...,62 NW 27th St,Mariscos,Seafood,4.7,145,62 NW 27th St,Seafood,4.7,145,62 NW 27th St

In [48]:
# # seleecionar columnas
# columnas = ['ciudad_residencia', 'edad','promedio_gasto_comida']
# df_copy[columnas]

# # modificar columna
# df_copy['promedio_gasto_comida'] = df_copy['promedio_gasto_comida'] * 1.1
# display(df_copy.head())

# # crear nueva columna
# df_copy['gasto_total'] = df_copy['promedio_gasto_comida'] * 10
# display(df_copy.head())

# # renombrar columna
# df_copy.rename(columns={'gasto_total': 'gasto_total_anual'}, inplace=True)
# display(df_copy.head())

# # reordenar columnas
# nueva_orden = ['ciudad_residencia', 'edad', 'promedio_gasto_comida', 'gasto_total_anual']
# df_copy = df_copy[nueva_orden]
# display(df_copy.head())

# # cMBIAR TIPO DE DATO
# df_copy['edad'] = df_copy['edad'].astype(float)

In [49]:
# agrupaciones
agrupado = df.groupby(['ciudad_residencia','genero'])['ingresos_mensuales'].sum()
# display(agrupado)

In [50]:
# filtrar filas
filtro = df_copy['ciudad_residencia'] == 'Miami'
df_filtrado = df_copy[filtro]
display(df_filtrado.head())

,id_persona,nombre,apellido,edad,genero,ciudad_residencia,estrato_socioeconomico,frecuencia_visita,promedio_gasto_comida,ocio,consume_licor,preferencias_alimenticias,membresia_premium,telefono_contacto,correo_electronico,tipo_de_pago_mas_usado,ingresos_mensuales
0,2550327378,Jackson,Gomez,31.0,Masculino,Miami,Alto,6,67.51,Sí,No,Vegetariano,Sí,(830)220-1926,No especificado,Efectivo,6425
16,6139475525,Andrew,Soto,18.0,Masculino,Miami,Muy Alto,9,26.60,Sí,Sí,Vegetariano,Sí,2859380942,ssteele@example.net,App,13452
37,5358661821,Elizabeth,Brown,79.0,Femenino,Miami,Muy Alto,6,28.43,No,No,Mariscos,Sí,(464)992-9070x38394,No especificado,Efectivo,14072
45,8593345998,Robert,Wilson,76.0,Masculino,Miami,Alto,5,43.00,Sí,No,Mariscos,Sí,NaN,No especificado,App,6528
47,6170452916,Bruce,Young,55.0,Masculino,Miami,Muy Alto,5,119.85,Sí,No,Carnes,Sí,NaN,ltran@example.com,Efectivo,15844

In [51]:
# quitar duplicados
df_sin_duplicados = df_copy.drop_duplicates()
display(df_sin_duplicados.head())

,id_persona,nombre,apellido,edad,genero,ciudad_residencia,estrato_socioeconomico,frecuencia_visita,promedio_gasto_comida,ocio,consume_licor,preferencias_alimenticias,membresia_premium,telefono_contacto,correo_electronico,tipo_de_pago_mas_usado,ingresos_mensuales
0,2550327378,Jackson,Gomez,31.0,Masculino,Miami,Alto,6,67.51,Sí,No,Vegetariano,Sí,(830)220-1926,No especificado,Efectivo,6425
1,9446112038,Samantha,Soto,40.0,Femenino,Denver,Medio,2,44.92,Sí,Sí,Mariscos,No,881-476-1426,No especificado,Efectivo,2374
2,3098363243,Terry,Adams,62.0,Femenino,Denver,Bajo,2,9.24,Sí,Sí,Vegetariano,No,NaN,diana74@example.net,Efectivo,1110
3,4013002847,James,Shannon,41.0,Masculino,Boston,Alto,5,30.74,Sí,Sí,Carnes,Sí,NaN,scottfrey@example.com,Tarjeta,6931
4,7372911048,Susan,Jones,49.0,Femenino,San Diego,Bajo,0,0.00,No,No,Carnes,No,243.248.8919,glassgary@example.org,Tarjeta,1350

In [52]:
# ciudades unicas
ciudades_unicas = df_copy['ciudad_residencia'].unique()
display(ciudades_unicas)

array(['Miami', 'Denver', 'Boston', 'San Diego', 'Dallas', 'NYC',
       'Seattle', 'Chicago', 'Houston', 'Phoenix'], dtype=object)

In [53]:
# El doble corchete [['...']] asegura que siga siendo un DataFrame
ciudades_unicas = df_copy[['ciudad_residencia']].drop_duplicates().reset_index(drop=True)
display(ciudades_unicas)

  ciudad_residencia
0             Miami
1            Denver
2            Boston
3         San Diego
4            Dallas
5               NYC
6           Seattle
7           Chicago
8           Houston
9           Phoenix